// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vlissides_bibliotheque.Data;

#nullable disable

namespace vlissides_bibliotheque.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221011163948_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "834684ee-d07f-470a-91ea-01feb16d2f90",
                            ConcurrencyStamp = "6494238c-5ee0-4d6a-925d-20f0e932e406",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "c2c54011-c8a3-44b7-a560-b76da1383d79",
                            ConcurrencyStamp = "69162fbd-767b-4ecd-8cc9-fd1fe2e0322f",
                            Name = "Utilisateur",
                            NormalizedName = "UTILISATEUR"
                        },
                        new
                        {
                            Id = "c7a578b8-1d4b-43c3-a85e-179d132e2aed",
                            ConcurrencyStamp = "9985b076-ab9a-4538-b692-34b21ed3d2e6",
                            Name = "Etudiant",
                            NormalizedName = "ETUDIANT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "83c10a40-c3f6-49bd-b230-f6975cc7befd",
                            RoleId = "834684ee-d07f-470a-91ea-01feb16d2f90"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Adresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("App")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCivique")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("AdresseId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Auteur", b =>
                {
                    b.Property<int>("AuteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("AuteurId");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.AuteurLivre", b =>
                {
                    b.Property<int>("AuteurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivreBibliothequeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuteurId", "LivreBibliothequeId");

                    b.HasIndex("LivreBibliothequeId");

                    b.ToTable("AuteursLivres");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.CommandeEtudiant", b =>
                {
                    b.Property<int>("FactureEtudiantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivreBibliothequeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("FactureEtudiantId", "LivreBibliothequeId");

                    b.HasIndex("LivreBibliothequeId");

                    b.ToTable("CommandesEtudiants");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Commanditaire", b =>
                {
                    b.Property<int>("CommanditaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("CommanditaireId");

                    b.ToTable("Commanditaires");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Cours", b =>
                {
                    b.Property<int>("CoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnneeParcours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgrammeEtudeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoursId");

                    b.HasIndex("ProgrammeEtudeId");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.CoursEtudiant", b =>
                {
                    b.Property<int>("CoursId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EtudiantId")
                        .HasColumnType("TEXT");

                    b.HasKey("CoursId", "EtudiantId");

                    b.HasIndex("EtudiantId");

                    b.ToTable("CoursEtudiant");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.CoursLivre", b =>
                {
                    b.Property<int>("CoursLivreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Complementaire")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoursId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivreBibliothequeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoursLivreId");

                    b.HasIndex("CoursId");

                    b.HasIndex("LivreBibliothequeId");

                    b.ToTable("CoursLivres");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.CoursProfesseur", b =>
                {
                    b.Property<int>("CoursId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfesseurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoursId", "ProfesseurId");

                    b.HasIndex("ProfesseurId");

                    b.ToTable("CoursProfesseurs");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.EtatLivre", b =>
                {
                    b.Property<int>("EtatLivreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EtatLivreId");

                    b.ToTable("EtatsLivres");

                    b.HasData(
                        new
                        {
                            EtatLivreId = 1,
                            Nom = "Neuf"
                        },
                        new
                        {
                            EtatLivreId = 2,
                            Nom = "Usagé"
                        },
                        new
                        {
                            EtatLivreId = 3,
                            Nom = "Numérique"
                        });
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Etoiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EtudiantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("EvaluationId");

                    b.HasIndex("EtudiantId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.EvaluationLivre", b =>
                {
                    b.Property<int>("EvaluationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivreBibliothequeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvaluationId", "LivreBibliothequeId");

                    b.HasIndex("LivreBibliothequeId");

                    b.ToTable("EvaluationsLivres");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Evenement", b =>
                {
                    b.Property<int>("EvenementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommanditaireId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Debut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("EvenementId");

                    b.HasIndex("CommanditaireId");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.FactureEtudiant", b =>
                {
                    b.Property<int>("FactureEtudiantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdresseLivraisonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateFacturation")
                        .HasColumnType("TEXT");

                    b.Property<string>("EtudiantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tps")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tvq")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypePaiementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FactureEtudiantId");

                    b.HasIndex("AdresseLivraisonId");

                    b.HasIndex("EtudiantId");

                    b.HasIndex("TypePaiementId");

                    b.ToTable("FactureEtudiant");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.LivreBibliotheque", b =>
                {
                    b.Property<int>("LivreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaisonEditionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoCouverture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("LivreId");

                    b.HasIndex("MaisonEditionId");

                    b.ToTable("LivresBibliotheque");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.LivreEtudiant", b =>
                {
                    b.Property<int>("LivreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("EtudiantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoCouverture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("LivreId");

                    b.HasIndex("EtudiantId");

                    b.ToTable("LivresEtudiants");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.MaisonEdition", b =>
                {
                    b.Property<int>("MaisonEditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaisonEditionId");

                    b.ToTable("MaisonsEditions");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.PrixEtatLivre", b =>
                {
                    b.Property<int>("PrixEtatLivreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatLivreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivreBibliothequeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Prix")
                        .HasColumnType("REAL");

                    b.HasKey("PrixEtatLivreId");

                    b.HasIndex("EtatLivreId");

                    b.HasIndex("LivreBibliothequeId");

                    b.ToTable("PrixEtatsLivres");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Professeur", b =>
                {
                    b.Property<int>("ProfesseurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProfesseurId");

                    b.ToTable("Professeurs");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.ProgrammeEtude", b =>
                {
                    b.Property<int>("ProgrammeEtudeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProgrammeEtudeId");

                    b.ToTable("ProgrammesEtudes");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.TypePaiement", b =>
                {
                    b.Property<int>("TypePaiementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TypePaiementId");

                    b.ToTable("TypesPaiement");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Utilisateur", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.ToTable("Utilisateurs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "83c10a40-c3f6-49bd-b230-f6975cc7befd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d67bb86f-d158-4f17-8142-49f7c65c082c",
                            Email = "gordon.john@gunclub-alabama.us",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GORDON.JOHN@GUNCLUB-ALABAMA.US",
                            NormalizedUserName = "GORDON.JOHN@GUNCLUB-ALABAMA.US",
                            PasswordHash = "AQAAAAEAACcQAAAAEPPTQfD4Wsa8pXZkOXxI7aQ1zh+9qSooJO3E9lHkI4K3HiK/bdIWQgtaWTc/ia3lBA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5469c667-1dbb-4a2c-9cd6-c3ba810f1c9a",
                            TwoFactorEnabled = false,
                            UserName = "gordon.john@gunclub-alabama.us",
                            Nom = "John",
                            Prenom = "Gordon"
                        });
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Etudiant", b =>
                {
                    b.HasBaseType("vlissides_bibliotheque.Models.Utilisateur");

                    b.Property<int>("AdresseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnneeParcours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgrammeEtudeId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AdresseId");

                    b.HasIndex("ProgrammeEtudeId");

                    b.ToTable("Etudiants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Adresse", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.AuteurLivre", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Auteur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.LivreBibliotheque", "LivreBibliotheque")
                        .WithMany()
                        .HasForeignKey("LivreBibliothequeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("LivreBibliotheque");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.CommandeEtudiant", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.FactureEtudiant", "FactureEtudiant")
                        .WithMany()
                        .HasForeignKey("FactureEtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.LivreBibliotheque", "LivreBibliotheque")
                        .WithMany()
                        .HasForeignKey("LivreBibliothequeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactureEtudiant");

                    b.Navigation("LivreBibliotheque");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Cours", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.ProgrammeEtude", "ProgrammeEtude")
                        .WithMany()
                        .HasForeignKey("ProgrammeEtudeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeEtude");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.CoursEtudiant", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Cours", "Cours")
                        .WithMany()
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.CoursLivre", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Cours", "Cours")
                        .WithMany()
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.LivreBibliotheque", "LivreBibliotheque")
                        .WithMany()
                        .HasForeignKey("LivreBibliothequeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("LivreBibliotheque");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.CoursProfesseur", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Cours", "Cours")
                        .WithMany()
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.Professeur", "Professeur")
                        .WithMany()
                        .HasForeignKey("ProfesseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Evaluation", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.EvaluationLivre", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.LivreBibliotheque", "LivreBibliotheque")
                        .WithMany()
                        .HasForeignKey("LivreBibliothequeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("LivreBibliotheque");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Evenement", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Commanditaire", "Commanditaire")
                        .WithMany()
                        .HasForeignKey("CommanditaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commanditaire");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.FactureEtudiant", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Adresse", "AdresseLivraison")
                        .WithMany()
                        .HasForeignKey("AdresseLivraisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.TypePaiement", "TypePaiement")
                        .WithMany()
                        .HasForeignKey("TypePaiementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdresseLivraison");

                    b.Navigation("Etudiant");

                    b.Navigation("TypePaiement");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.LivreBibliotheque", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.MaisonEdition", "MaisonEdition")
                        .WithMany()
                        .HasForeignKey("MaisonEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaisonEdition");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.LivreEtudiant", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.PrixEtatLivre", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.EtatLivre", "EtatLivre")
                        .WithMany()
                        .HasForeignKey("EtatLivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.LivreBibliotheque", "LivreBibliotheque")
                        .WithMany()
                        .HasForeignKey("LivreBibliothequeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtatLivre");

                    b.Navigation("LivreBibliotheque");
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Utilisateur", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("vlissides_bibliotheque.Models.Utilisateur", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vlissides_bibliotheque.Models.Etudiant", b =>
                {
                    b.HasOne("vlissides_bibliotheque.Models.Adresse", "Adresse")
                        .WithMany()
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.Utilisateur", null)
                        .WithOne()
                        .HasForeignKey("vlissides_bibliotheque.Models.Etudiant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vlissides_bibliotheque.Models.ProgrammeEtude", "ProgrammeEtude")
                        .WithMany()
                        .HasForeignKey("ProgrammeEtudeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Adresse");

                    b.Navigation("ProgrammeEtude");
                });
#pragma warning restore 612, 618
        }
    }
}
